name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liFjMqktWX9noOZj"
GITHUB_OWNER = "Abcdbin"
GITHUB_REPO = "NavSphere-cf"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://dh.52016889.xyz/api/auth"
NEXT_PUBLIC_API_URL="https://dh.52016889.xyz/"

